// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"
	"database/sql"
)

const commitSnapshot = `-- name: CommitSnapshot :exec
UPDATE snapshots
SET status = 'committed', manifest_object_key = ?, logical_bytes = ?, stored_bytes = ?, stream_sha256 = ?, stream_from_guid = ?, stream_to_guid = ?, chunk_count = ?, upload_completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type CommitSnapshotParams struct {
	ManifestObjectKey sql.NullString `json:"manifest_object_key"`
	LogicalBytes      sql.NullInt64  `json:"logical_bytes"`
	StoredBytes       int64          `json:"stored_bytes"`
	StreamSha256      sql.NullString `json:"stream_sha256"`
	StreamFromGuid    string         `json:"stream_from_guid"`
	StreamToGuid      string         `json:"stream_to_guid"`
	ChunkCount        int64          `json:"chunk_count"`
	ID                string         `json:"id"`
}

func (q *Queries) CommitSnapshot(ctx context.Context, arg CommitSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, commitSnapshot,
		arg.ManifestObjectKey,
		arg.LogicalBytes,
		arg.StoredBytes,
		arg.StreamSha256,
		arg.StreamFromGuid,
		arg.StreamToGuid,
		arg.ChunkCount,
		arg.ID,
	)
	return err
}

const completeUploadSession = `-- name: CompleteUploadSession :exec
UPDATE upload_sessions
SET status = 'complete', bytes_received = ?, chunks_completed = ?, stream_sha256 = ?, manifest_object_key = ?, completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type CompleteUploadSessionParams struct {
	BytesReceived     int64          `json:"bytes_received"`
	ChunksCompleted   int64          `json:"chunks_completed"`
	StreamSha256      sql.NullString `json:"stream_sha256"`
	ManifestObjectKey sql.NullString `json:"manifest_object_key"`
	ID                string         `json:"id"`
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) error {
	_, err := q.db.ExecContext(ctx, completeUploadSession,
		arg.BytesReceived,
		arg.ChunksCompleted,
		arg.StreamSha256,
		arg.ManifestObjectKey,
		arg.ID,
	)
	return err
}

const completeValidationJob = `-- name: CompleteValidationJob :exec
UPDATE validation_jobs
SET status = 'succeeded', completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), result_summary = ?
WHERE id = ?
`

type CompleteValidationJobParams struct {
	ResultSummary sql.NullString `json:"result_summary"`
	ID            string         `json:"id"`
}

func (q *Queries) CompleteValidationJob(ctx context.Context, arg CompleteValidationJobParams) error {
	_, err := q.db.ExecContext(ctx, completeValidationJob, arg.ResultSummary, arg.ID)
	return err
}

const countCommittedDescendants = `-- name: CountCommittedDescendants :one
WITH RECURSIVE descendants(id) AS (
  SELECT s.id
  FROM snapshots s
  WHERE s.parent_snapshot_id = ?
    AND s.status = 'committed'
  UNION ALL
  SELECT child.id
  FROM snapshots child
  JOIN descendants ON child.parent_snapshot_id = descendants.id
  WHERE child.status = 'committed'
)
SELECT count(*) AS count
FROM descendants
`

func (q *Queries) CountCommittedDescendants(ctx context.Context, parentSnapshotID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommittedDescendants, parentSnapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommittedSnapshots = `-- name: CountCommittedSnapshots :one
SELECT count(*) AS count
FROM snapshots
WHERE status = 'committed'
`

func (q *Queries) CountCommittedSnapshots(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommittedSnapshots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDatasets = `-- name: CountDatasets :one
SELECT count(*) AS count
FROM datasets
`

func (q *Queries) CountDatasets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDatasets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedUploads = `-- name: CountFailedUploads :one
SELECT count(*) AS count
FROM upload_sessions
WHERE status = 'failed'
`

func (q *Queries) CountFailedUploads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedUploads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedValidations = `-- name: CountFailedValidations :one
SELECT count(*) AS count
FROM snapshots
WHERE status = 'committed'
  AND chain_validation_status = 'failed'
`

func (q *Queries) CountFailedValidations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedValidations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSources = `-- name: CountSources :one
SELECT count(*) AS count
FROM sources
`

func (q *Queries) CountSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, name, token_hash, token_prefix)
VALUES (?, ?, ?, ?)
`

type CreateAPITokenParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	TokenHash   string `json:"token_hash"`
	TokenPrefix string `json:"token_prefix"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
	)
	return err
}

const createCatalogBackup = `-- name: CreateCatalogBackup :exec
INSERT INTO catalog_backups (id, operation_id, object_key, metadata_object_key, size_bytes, checksum_sha256, started_at, completed_at, status, failure_reason)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCatalogBackupParams struct {
	ID                string         `json:"id"`
	OperationID       sql.NullString `json:"operation_id"`
	ObjectKey         string         `json:"object_key"`
	MetadataObjectKey sql.NullString `json:"metadata_object_key"`
	SizeBytes         int64          `json:"size_bytes"`
	ChecksumSha256    string         `json:"checksum_sha256"`
	StartedAt         string         `json:"started_at"`
	CompletedAt       sql.NullString `json:"completed_at"`
	Status            string         `json:"status"`
	FailureReason     sql.NullString `json:"failure_reason"`
}

func (q *Queries) CreateCatalogBackup(ctx context.Context, arg CreateCatalogBackupParams) error {
	_, err := q.db.ExecContext(ctx, createCatalogBackup,
		arg.ID,
		arg.OperationID,
		arg.ObjectKey,
		arg.MetadataObjectKey,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Status,
		arg.FailureReason,
	)
	return err
}

const createDataset = `-- name: CreateDataset :exec
INSERT INTO datasets (id, source_id, pool_id, path, display_name, last_seen_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type CreateDatasetParams struct {
	ID          string `json:"id"`
	SourceID    string `json:"source_id"`
	PoolID      string `json:"pool_id"`
	Path        string `json:"path"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateDataset(ctx context.Context, arg CreateDatasetParams) error {
	_, err := q.db.ExecContext(ctx, createDataset,
		arg.ID,
		arg.SourceID,
		arg.PoolID,
		arg.Path,
		arg.DisplayName,
	)
	return err
}

const createOperation = `-- name: CreateOperation :exec
INSERT INTO operations (id, type, status, source_id, pool_id, dataset_id, snapshot_id, upload_session_id, summary)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOperationParams struct {
	ID              string         `json:"id"`
	Type            string         `json:"type"`
	Status          string         `json:"status"`
	SourceID        sql.NullString `json:"source_id"`
	PoolID          sql.NullString `json:"pool_id"`
	DatasetID       sql.NullString `json:"dataset_id"`
	SnapshotID      sql.NullString `json:"snapshot_id"`
	UploadSessionID sql.NullString `json:"upload_session_id"`
	Summary         sql.NullString `json:"summary"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) error {
	_, err := q.db.ExecContext(ctx, createOperation,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.SourceID,
		arg.PoolID,
		arg.DatasetID,
		arg.SnapshotID,
		arg.UploadSessionID,
		arg.Summary,
	)
	return err
}

const createPendingSnapshot = `-- name: CreatePendingSnapshot :exec
INSERT INTO snapshots (id, dataset_id, name, parent_snapshot_id, status, upload_started_at)
VALUES (?, ?, ?, ?, 'uploading', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type CreatePendingSnapshotParams struct {
	ID               string         `json:"id"`
	DatasetID        string         `json:"dataset_id"`
	Name             string         `json:"name"`
	ParentSnapshotID sql.NullString `json:"parent_snapshot_id"`
}

func (q *Queries) CreatePendingSnapshot(ctx context.Context, arg CreatePendingSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createPendingSnapshot,
		arg.ID,
		arg.DatasetID,
		arg.Name,
		arg.ParentSnapshotID,
	)
	return err
}

const createPool = `-- name: CreatePool :exec
INSERT INTO pools (id, source_id, name, last_seen_at)
VALUES (?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type CreatePoolParams struct {
	ID       string `json:"id"`
	SourceID string `json:"source_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreatePool(ctx context.Context, arg CreatePoolParams) error {
	_, err := q.db.ExecContext(ctx, createPool, arg.ID, arg.SourceID, arg.Name)
	return err
}

const createSSHKey = `-- name: CreateSSHKey :exec
INSERT INTO ssh_keys (id, name, public_key, fingerprint_sha256)
VALUES (?, ?, ?, ?)
`

type CreateSSHKeyParams struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	PublicKey         string `json:"public_key"`
	FingerprintSha256 string `json:"fingerprint_sha256"`
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSSHKey,
		arg.ID,
		arg.Name,
		arg.PublicKey,
		arg.FingerprintSha256,
	)
	return err
}

const createSnapshotChunk = `-- name: CreateSnapshotChunk :exec
INSERT INTO snapshot_chunks (id, snapshot_id, upload_session_id, chunk_index, object_key, size_bytes, zfs_offset_start, zfs_offset_end, sha256, status, completed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'verified', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type CreateSnapshotChunkParams struct {
	ID              string `json:"id"`
	SnapshotID      string `json:"snapshot_id"`
	UploadSessionID string `json:"upload_session_id"`
	ChunkIndex      int64  `json:"chunk_index"`
	ObjectKey       string `json:"object_key"`
	SizeBytes       int64  `json:"size_bytes"`
	ZfsOffsetStart  int64  `json:"zfs_offset_start"`
	ZfsOffsetEnd    int64  `json:"zfs_offset_end"`
	Sha256          string `json:"sha256"`
}

func (q *Queries) CreateSnapshotChunk(ctx context.Context, arg CreateSnapshotChunkParams) error {
	_, err := q.db.ExecContext(ctx, createSnapshotChunk,
		arg.ID,
		arg.SnapshotID,
		arg.UploadSessionID,
		arg.ChunkIndex,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ZfsOffsetStart,
		arg.ZfsOffsetEnd,
		arg.Sha256,
	)
	return err
}

const createSource = `-- name: CreateSource :exec
INSERT INTO sources (id, name, description, last_seen_at)
VALUES (?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type CreateSourceParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) error {
	_, err := q.db.ExecContext(ctx, createSource, arg.ID, arg.Name, arg.Description)
	return err
}

const createUploadSession = `-- name: CreateUploadSession :exec
INSERT INTO upload_sessions (id, dataset_id, snapshot_id, target_snapshot_name, base_snapshot_id, status, chunk_size_bytes)
VALUES (?, ?, ?, ?, ?, 'uploading', ?)
`

type CreateUploadSessionParams struct {
	ID                 string         `json:"id"`
	DatasetID          string         `json:"dataset_id"`
	SnapshotID         sql.NullString `json:"snapshot_id"`
	TargetSnapshotName string         `json:"target_snapshot_name"`
	BaseSnapshotID     sql.NullString `json:"base_snapshot_id"`
	ChunkSizeBytes     int64          `json:"chunk_size_bytes"`
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUploadSession,
		arg.ID,
		arg.DatasetID,
		arg.SnapshotID,
		arg.TargetSnapshotName,
		arg.BaseSnapshotID,
		arg.ChunkSizeBytes,
	)
	return err
}

const createValidationJob = `-- name: CreateValidationJob :exec
INSERT INTO validation_jobs (id, snapshot_id, type, executor, status, started_at, result_summary)
VALUES (?, ?, ?, ?, 'running', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), ?)
`

type CreateValidationJobParams struct {
	ID            string         `json:"id"`
	SnapshotID    sql.NullString `json:"snapshot_id"`
	Type          string         `json:"type"`
	Executor      string         `json:"executor"`
	ResultSummary sql.NullString `json:"result_summary"`
}

func (q *Queries) CreateValidationJob(ctx context.Context, arg CreateValidationJobParams) error {
	_, err := q.db.ExecContext(ctx, createValidationJob,
		arg.ID,
		arg.SnapshotID,
		arg.Type,
		arg.Executor,
		arg.ResultSummary,
	)
	return err
}

const createValidationOperation = `-- name: CreateValidationOperation :exec
INSERT INTO operations (id, type, status, snapshot_id, validation_job_id, summary)
VALUES (?, 'validation', 'running', ?, ?, ?)
`

type CreateValidationOperationParams struct {
	ID              string         `json:"id"`
	SnapshotID      sql.NullString `json:"snapshot_id"`
	ValidationJobID sql.NullString `json:"validation_job_id"`
	Summary         sql.NullString `json:"summary"`
}

func (q *Queries) CreateValidationOperation(ctx context.Context, arg CreateValidationOperationParams) error {
	_, err := q.db.ExecContext(ctx, createValidationOperation,
		arg.ID,
		arg.SnapshotID,
		arg.ValidationJobID,
		arg.Summary,
	)
	return err
}

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings
WHERE key = ?
`

func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteAppSetting, key)
	return err
}

const deleteCatalogBackup = `-- name: DeleteCatalogBackup :exec
DELETE FROM catalog_backups
WHERE id = ?
`

func (q *Queries) DeleteCatalogBackup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCatalogBackup, id)
	return err
}

const deleteDataset = `-- name: DeleteDataset :exec
DELETE FROM datasets
WHERE id = ?
`

func (q *Queries) DeleteDataset(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDataset, id)
	return err
}

const deleteSSHKey = `-- name: DeleteSSHKey :exec
DELETE FROM ssh_keys
WHERE id = ?
`

func (q *Queries) DeleteSSHKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSSHKey, id)
	return err
}

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots
WHERE id = ?
`

func (q *Queries) DeleteSnapshot(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshot, id)
	return err
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions
WHERE id = ?
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSession, id)
	return err
}

const deleteUploadSessionsBySnapshot = `-- name: DeleteUploadSessionsBySnapshot :exec
DELETE FROM upload_sessions
WHERE snapshot_id = ?
`

func (q *Queries) DeleteUploadSessionsBySnapshot(ctx context.Context, snapshotID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSessionsBySnapshot, snapshotID)
	return err
}

const ensureAdminCredentials = `-- name: EnsureAdminCredentials :exec
INSERT OR IGNORE INTO admin_credentials (singleton, password_hash)
VALUES (1, ?)
`

func (q *Queries) EnsureAdminCredentials(ctx context.Context, passwordHash sql.NullString) error {
	_, err := q.db.ExecContext(ctx, ensureAdminCredentials, passwordHash)
	return err
}

const failOperationByUploadSession = `-- name: FailOperationByUploadSession :exec
UPDATE operations
SET status = 'failed', summary = ?, failure_reason = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE upload_session_id = ?
  AND status IN ('queued', 'running')
`

type FailOperationByUploadSessionParams struct {
	Summary         sql.NullString `json:"summary"`
	FailureReason   sql.NullString `json:"failure_reason"`
	UploadSessionID sql.NullString `json:"upload_session_id"`
}

func (q *Queries) FailOperationByUploadSession(ctx context.Context, arg FailOperationByUploadSessionParams) error {
	_, err := q.db.ExecContext(ctx, failOperationByUploadSession, arg.Summary, arg.FailureReason, arg.UploadSessionID)
	return err
}

const failSnapshot = `-- name: FailSnapshot :exec
UPDATE snapshots
SET status = 'failed', failure_reason = ?
WHERE id = ?
`

type FailSnapshotParams struct {
	FailureReason sql.NullString `json:"failure_reason"`
	ID            string         `json:"id"`
}

func (q *Queries) FailSnapshot(ctx context.Context, arg FailSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, failSnapshot, arg.FailureReason, arg.ID)
	return err
}

const failUploadSession = `-- name: FailUploadSession :exec
UPDATE upload_sessions
SET status = 'failed', failure_reason = ?, completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FailUploadSessionParams struct {
	FailureReason sql.NullString `json:"failure_reason"`
	ID            string         `json:"id"`
}

func (q *Queries) FailUploadSession(ctx context.Context, arg FailUploadSessionParams) error {
	_, err := q.db.ExecContext(ctx, failUploadSession, arg.FailureReason, arg.ID)
	return err
}

const failValidationJob = `-- name: FailValidationJob :exec
UPDATE validation_jobs
SET status = 'failed', completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), result_summary = ?
WHERE id = ?
`

type FailValidationJobParams struct {
	ResultSummary sql.NullString `json:"result_summary"`
	ID            string         `json:"id"`
}

func (q *Queries) FailValidationJob(ctx context.Context, arg FailValidationJobParams) error {
	_, err := q.db.ExecContext(ctx, failValidationJob, arg.ResultSummary, arg.ID)
	return err
}

const getActiveAPITokenByHash = `-- name: GetActiveAPITokenByHash :one
SELECT id, name, token_prefix, created_at, last_used_at, revoked_at
FROM api_tokens
WHERE token_hash = ?
  AND revoked_at IS NULL
`

type GetActiveAPITokenByHashRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	TokenPrefix string         `json:"token_prefix"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

func (q *Queries) GetActiveAPITokenByHash(ctx context.Context, tokenHash string) (GetActiveAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAPITokenByHash, tokenHash)
	var i GetActiveAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminCredentials = `-- name: GetAdminCredentials :one
SELECT singleton, password_hash, created_at
FROM admin_credentials
WHERE singleton = 1
`

func (q *Queries) GetAdminCredentials(ctx context.Context) (AdminCredential, error) {
	row := q.db.QueryRowContext(ctx, getAdminCredentials)
	var i AdminCredential
	err := row.Scan(&i.Singleton, &i.PasswordHash, &i.CreatedAt)
	return i, err
}

const getCommittedSnapshotByToGUID = `-- name: GetCommittedSnapshotByToGUID :one
SELECT s.id, s.name, s.status, s.stream_to_guid
FROM snapshots s
JOIN datasets d ON d.id = s.dataset_id
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
WHERE src.name = ?
  AND p.name = ?
  AND d.path = ?
  AND s.stream_to_guid = ?
  AND s.status = 'committed'
`

type GetCommittedSnapshotByToGUIDParams struct {
	Name         string `json:"name"`
	Name_2       string `json:"name_2"`
	Path         string `json:"path"`
	StreamToGuid string `json:"stream_to_guid"`
}

type GetCommittedSnapshotByToGUIDRow struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Status       string `json:"status"`
	StreamToGuid string `json:"stream_to_guid"`
}

func (q *Queries) GetCommittedSnapshotByToGUID(ctx context.Context, arg GetCommittedSnapshotByToGUIDParams) (GetCommittedSnapshotByToGUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommittedSnapshotByToGUID,
		arg.Name,
		arg.Name_2,
		arg.Path,
		arg.StreamToGuid,
	)
	var i GetCommittedSnapshotByToGUIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.StreamToGuid,
	)
	return i, err
}

const getDatasetByPath = `-- name: GetDatasetByPath :one
SELECT id, source_id, pool_id, path, display_name, created_at, last_seen_at
FROM datasets
WHERE source_id = ? AND pool_id = ? AND path = ?
`

type GetDatasetByPathParams struct {
	SourceID string `json:"source_id"`
	PoolID   string `json:"pool_id"`
	Path     string `json:"path"`
}

func (q *Queries) GetDatasetByPath(ctx context.Context, arg GetDatasetByPathParams) (Dataset, error) {
	row := q.db.QueryRowContext(ctx, getDatasetByPath, arg.SourceID, arg.PoolID, arg.Path)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.PoolID,
		&i.Path,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getDatasetDetail = `-- name: GetDatasetDetail :one
SELECT d.id AS dataset_id,
       src.name AS source_name,
       p.name AS pool_name,
       d.path AS dataset_path,
       d.created_at,
       d.last_seen_at
FROM datasets d
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
WHERE d.id = ?
`

type GetDatasetDetailRow struct {
	DatasetID   string         `json:"dataset_id"`
	SourceName  string         `json:"source_name"`
	PoolName    string         `json:"pool_name"`
	DatasetPath string         `json:"dataset_path"`
	CreatedAt   string         `json:"created_at"`
	LastSeenAt  sql.NullString `json:"last_seen_at"`
}

func (q *Queries) GetDatasetDetail(ctx context.Context, id string) (GetDatasetDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getDatasetDetail, id)
	var i GetDatasetDetailRow
	err := row.Scan(
		&i.DatasetID,
		&i.SourceName,
		&i.PoolName,
		&i.DatasetPath,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getLatestCatalogBackup = `-- name: GetLatestCatalogBackup :one
SELECT id, operation_id, object_key, metadata_object_key, size_bytes, checksum_sha256, started_at, completed_at, status, failure_reason
FROM catalog_backups
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCatalogBackup(ctx context.Context) (CatalogBackup, error) {
	row := q.db.QueryRowContext(ctx, getLatestCatalogBackup)
	var i CatalogBackup
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.ObjectKey,
		&i.MetadataObjectKey,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.FailureReason,
	)
	return i, err
}

const getLatestOperations = `-- name: GetLatestOperations :many
SELECT id, type, status, started_at, updated_at, completed_at, summary, failure_reason
FROM operations
WHERE type != 'catalog_backup'
ORDER BY started_at DESC
LIMIT ?
`

type GetLatestOperationsRow struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Status        string         `json:"status"`
	StartedAt     string         `json:"started_at"`
	UpdatedAt     string         `json:"updated_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
	Summary       sql.NullString `json:"summary"`
	FailureReason sql.NullString `json:"failure_reason"`
}

func (q *Queries) GetLatestOperations(ctx context.Context, limit int64) ([]GetLatestOperationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestOperationsRow
	for rows.Next() {
		var i GetLatestOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Summary,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPoolByName = `-- name: GetPoolByName :one
SELECT id, source_id, name, created_at, last_seen_at
FROM pools
WHERE source_id = ? AND name = ?
`

type GetPoolByNameParams struct {
	SourceID string `json:"source_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetPoolByName(ctx context.Context, arg GetPoolByNameParams) (Pool, error) {
	row := q.db.QueryRowContext(ctx, getPoolByName, arg.SourceID, arg.Name)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSSHKeyByFingerprint = `-- name: GetSSHKeyByFingerprint :one
SELECT id, name, public_key, fingerprint_sha256, created_at, last_used_at
FROM ssh_keys
WHERE fingerprint_sha256 = ?
`

func (q *Queries) GetSSHKeyByFingerprint(ctx context.Context, fingerprintSha256 string) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, getSSHKeyByFingerprint, fingerprintSha256)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.FingerprintSha256,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSnapshotByName = `-- name: GetSnapshotByName :one
SELECT id, dataset_id, name, parent_snapshot_id, manifest_object_key, status,
       stream_validation_status, chain_validation_status,
       logical_bytes, stored_bytes, stream_sha256, stream_from_guid, stream_to_guid, chunk_count, created_at, upload_started_at,
       upload_completed_at, failure_reason
FROM snapshots
WHERE dataset_id = ? AND name = ?
`

type GetSnapshotByNameParams struct {
	DatasetID string `json:"dataset_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetSnapshotByName(ctx context.Context, arg GetSnapshotByNameParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByName, arg.DatasetID, arg.Name)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Name,
		&i.ParentSnapshotID,
		&i.ManifestObjectKey,
		&i.Status,
		&i.StreamValidationStatus,
		&i.ChainValidationStatus,
		&i.LogicalBytes,
		&i.StoredBytes,
		&i.StreamSha256,
		&i.StreamFromGuid,
		&i.StreamToGuid,
		&i.ChunkCount,
		&i.CreatedAt,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.FailureReason,
	)
	return i, err
}

const getSnapshotDetail = `-- name: GetSnapshotDetail :one
SELECT s.id AS snapshot_id,
       s.name AS snapshot_name,
       s.parent_snapshot_id,
       s.manifest_object_key,
       s.status,
       s.stream_validation_status,
       s.chain_validation_status,
       s.logical_bytes,
       s.stored_bytes,
       s.stream_sha256,
       s.stream_from_guid,
       s.stream_to_guid,
       s.chunk_count,
       s.upload_started_at,
       s.upload_completed_at,
       s.failure_reason,
       d.id AS dataset_id,
       d.path AS dataset_path,
       src.name AS source_name,
       p.name AS pool_name
FROM snapshots s
JOIN datasets d ON d.id = s.dataset_id
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
WHERE s.id = ?
`

type GetSnapshotDetailRow struct {
	SnapshotID             string         `json:"snapshot_id"`
	SnapshotName           string         `json:"snapshot_name"`
	ParentSnapshotID       sql.NullString `json:"parent_snapshot_id"`
	ManifestObjectKey      sql.NullString `json:"manifest_object_key"`
	Status                 string         `json:"status"`
	StreamValidationStatus string         `json:"stream_validation_status"`
	ChainValidationStatus  string         `json:"chain_validation_status"`
	LogicalBytes           sql.NullInt64  `json:"logical_bytes"`
	StoredBytes            int64          `json:"stored_bytes"`
	StreamSha256           sql.NullString `json:"stream_sha256"`
	StreamFromGuid         string         `json:"stream_from_guid"`
	StreamToGuid           string         `json:"stream_to_guid"`
	ChunkCount             int64          `json:"chunk_count"`
	UploadStartedAt        sql.NullString `json:"upload_started_at"`
	UploadCompletedAt      sql.NullString `json:"upload_completed_at"`
	FailureReason          sql.NullString `json:"failure_reason"`
	DatasetID              string         `json:"dataset_id"`
	DatasetPath            string         `json:"dataset_path"`
	SourceName             string         `json:"source_name"`
	PoolName               string         `json:"pool_name"`
}

func (q *Queries) GetSnapshotDetail(ctx context.Context, id string) (GetSnapshotDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotDetail, id)
	var i GetSnapshotDetailRow
	err := row.Scan(
		&i.SnapshotID,
		&i.SnapshotName,
		&i.ParentSnapshotID,
		&i.ManifestObjectKey,
		&i.Status,
		&i.StreamValidationStatus,
		&i.ChainValidationStatus,
		&i.LogicalBytes,
		&i.StoredBytes,
		&i.StreamSha256,
		&i.StreamFromGuid,
		&i.StreamToGuid,
		&i.ChunkCount,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.FailureReason,
		&i.DatasetID,
		&i.DatasetPath,
		&i.SourceName,
		&i.PoolName,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, description, created_at, last_seen_at
FROM sources
WHERE name = ?
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByName, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const invalidateDatasetSnapshotsForDeletion = `-- name: InvalidateDatasetSnapshotsForDeletion :exec
UPDATE snapshots
SET status = 'deleting',
    stream_validation_status = 'failed',
    chain_validation_status = 'failed',
    failure_reason = 'deletion in progress'
WHERE dataset_id = ?
`

func (q *Queries) InvalidateDatasetSnapshotsForDeletion(ctx context.Context, datasetID string) error {
	_, err := q.db.ExecContext(ctx, invalidateDatasetSnapshotsForDeletion, datasetID)
	return err
}

const invalidateSnapshotForDeletion = `-- name: InvalidateSnapshotForDeletion :exec
UPDATE snapshots
SET status = 'deleting',
    stream_validation_status = 'failed',
    chain_validation_status = 'failed',
    failure_reason = 'deletion in progress'
WHERE id = ?
`

func (q *Queries) InvalidateSnapshotForDeletion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, invalidateSnapshotForDeletion, id)
	return err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, token_prefix, created_at, last_used_at, revoked_at
FROM api_tokens
ORDER BY created_at DESC
`

type ListAPITokensRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	TokenPrefix string         `json:"token_prefix"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

func (q *Queries) ListAPITokens(ctx context.Context) ([]ListAPITokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensRow
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAbandonedUploadSessions = `-- name: ListAbandonedUploadSessions :many
SELECT id, dataset_id, snapshot_id, target_snapshot_name, base_snapshot_id, status,
       chunk_size_bytes, current_chunk_index, chunks_completed, bytes_received, stream_sha256,
       manifest_object_key, started_at, last_heartbeat_at, completed_at, failure_reason
FROM upload_sessions
WHERE status IN ('failed', 'aborted')
  AND coalesce(completed_at, last_heartbeat_at, started_at) < ?
ORDER BY coalesce(completed_at, last_heartbeat_at, started_at) ASC
LIMIT ?
`

type ListAbandonedUploadSessionsParams struct {
	CompletedAt sql.NullString `json:"completed_at"`
	Limit       int64          `json:"limit"`
}

func (q *Queries) ListAbandonedUploadSessions(ctx context.Context, arg ListAbandonedUploadSessionsParams) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, listAbandonedUploadSessions, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.SnapshotID,
			&i.TargetSnapshotName,
			&i.BaseSnapshotID,
			&i.Status,
			&i.ChunkSizeBytes,
			&i.CurrentChunkIndex,
			&i.ChunksCompleted,
			&i.BytesReceived,
			&i.StreamSha256,
			&i.ManifestObjectKey,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.CompletedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUploads = `-- name: ListActiveUploads :many
SELECT u.id AS upload_session_id,
       src.name AS source_name,
       p.name AS pool_name,
       d.path AS dataset_path,
       u.target_snapshot_name,
       u.status,
       u.bytes_received,
       u.chunks_completed,
       u.started_at,
       u.last_heartbeat_at
FROM upload_sessions u
JOIN datasets d ON d.id = u.dataset_id
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
WHERE u.status IN ('pending', 'uploading', 'writing_chunk', 'committing_manifest', 'committing_catalog')
ORDER BY u.last_heartbeat_at DESC
`

type ListActiveUploadsRow struct {
	UploadSessionID    string `json:"upload_session_id"`
	SourceName         string `json:"source_name"`
	PoolName           string `json:"pool_name"`
	DatasetPath        string `json:"dataset_path"`
	TargetSnapshotName string `json:"target_snapshot_name"`
	Status             string `json:"status"`
	BytesReceived      int64  `json:"bytes_received"`
	ChunksCompleted    int64  `json:"chunks_completed"`
	StartedAt          string `json:"started_at"`
	LastHeartbeatAt    string `json:"last_heartbeat_at"`
}

func (q *Queries) ListActiveUploads(ctx context.Context) ([]ListActiveUploadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUploadsRow
	for rows.Next() {
		var i ListActiveUploadsRow
		if err := rows.Scan(
			&i.UploadSessionID,
			&i.SourceName,
			&i.PoolName,
			&i.DatasetPath,
			&i.TargetSnapshotName,
			&i.Status,
			&i.BytesReceived,
			&i.ChunksCompleted,
			&i.StartedAt,
			&i.LastHeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at
FROM app_settings
ORDER BY key
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogBackupsOlderThan = `-- name: ListCatalogBackupsOlderThan :many
SELECT id, operation_id, object_key, metadata_object_key, size_bytes, checksum_sha256, started_at, completed_at, status, failure_reason
FROM catalog_backups
WHERE started_at < ?
ORDER BY started_at ASC
LIMIT ?
`

type ListCatalogBackupsOlderThanParams struct {
	StartedAt string `json:"started_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListCatalogBackupsOlderThan(ctx context.Context, arg ListCatalogBackupsOlderThanParams) ([]CatalogBackup, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogBackupsOlderThan, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogBackup
	for rows.Next() {
		var i CatalogBackup
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.ObjectKey,
			&i.MetadataObjectKey,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommittedChildSnapshots = `-- name: ListCommittedChildSnapshots :many
SELECT id, name
FROM snapshots
WHERE parent_snapshot_id = ?
  AND status = 'committed'
ORDER BY created_at ASC
`

type ListCommittedChildSnapshotsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListCommittedChildSnapshots(ctx context.Context, parentSnapshotID sql.NullString) ([]ListCommittedChildSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommittedChildSnapshots, parentSnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommittedChildSnapshotsRow
	for rows.Next() {
		var i ListCommittedChildSnapshotsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommittedSnapshotsForIdentity = `-- name: ListCommittedSnapshotsForIdentity :many
SELECT s.id,
       s.name,
       parent.name AS parent_snapshot_name,
       s.manifest_object_key,
       s.status,
       s.stream_validation_status,
       s.chain_validation_status,
       s.stream_sha256,
       s.stream_from_guid,
       s.stream_to_guid,
       s.chunk_count,
       s.upload_completed_at
FROM snapshots s
JOIN datasets d ON d.id = s.dataset_id
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
LEFT JOIN snapshots parent ON parent.id = s.parent_snapshot_id
WHERE src.name = ?
  AND p.name = ?
  AND d.path = ?
  AND s.status = 'committed'
  AND s.manifest_object_key IS NOT NULL
ORDER BY s.created_at ASC
`

type ListCommittedSnapshotsForIdentityParams struct {
	Name   string `json:"name"`
	Name_2 string `json:"name_2"`
	Path   string `json:"path"`
}

type ListCommittedSnapshotsForIdentityRow struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	ParentSnapshotName     sql.NullString `json:"parent_snapshot_name"`
	ManifestObjectKey      sql.NullString `json:"manifest_object_key"`
	Status                 string         `json:"status"`
	StreamValidationStatus string         `json:"stream_validation_status"`
	ChainValidationStatus  string         `json:"chain_validation_status"`
	StreamSha256           sql.NullString `json:"stream_sha256"`
	StreamFromGuid         string         `json:"stream_from_guid"`
	StreamToGuid           string         `json:"stream_to_guid"`
	ChunkCount             int64          `json:"chunk_count"`
	UploadCompletedAt      sql.NullString `json:"upload_completed_at"`
}

func (q *Queries) ListCommittedSnapshotsForIdentity(ctx context.Context, arg ListCommittedSnapshotsForIdentityParams) ([]ListCommittedSnapshotsForIdentityRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommittedSnapshotsForIdentity, arg.Name, arg.Name_2, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommittedSnapshotsForIdentityRow
	for rows.Next() {
		var i ListCommittedSnapshotsForIdentityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentSnapshotName,
			&i.ManifestObjectKey,
			&i.Status,
			&i.StreamValidationStatus,
			&i.ChainValidationStatus,
			&i.StreamSha256,
			&i.StreamFromGuid,
			&i.StreamToGuid,
			&i.ChunkCount,
			&i.UploadCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasetObjectKeys = `-- name: ListDatasetObjectKeys :many
SELECT sc.object_key
FROM snapshot_chunks sc
JOIN snapshots s ON s.id = sc.snapshot_id
WHERE s.dataset_id = ?
UNION
SELECT s.manifest_object_key AS object_key
FROM snapshots s
WHERE s.dataset_id = ?
  AND s.manifest_object_key IS NOT NULL
  AND s.manifest_object_key != ''
`

type ListDatasetObjectKeysParams struct {
	DatasetID   string `json:"dataset_id"`
	DatasetID_2 string `json:"dataset_id_2"`
}

func (q *Queries) ListDatasetObjectKeys(ctx context.Context, arg ListDatasetObjectKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDatasetObjectKeys, arg.DatasetID, arg.DatasetID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasetSnapshots = `-- name: ListDatasetSnapshots :many
SELECT id, name, parent_snapshot_id, manifest_object_key, status,
       stream_validation_status, chain_validation_status,
       stored_bytes, stream_sha256, stream_from_guid, stream_to_guid, chunk_count, upload_started_at, upload_completed_at, failure_reason
FROM snapshots
WHERE dataset_id = ?
ORDER BY created_at DESC
`

type ListDatasetSnapshotsRow struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	ParentSnapshotID       sql.NullString `json:"parent_snapshot_id"`
	ManifestObjectKey      sql.NullString `json:"manifest_object_key"`
	Status                 string         `json:"status"`
	StreamValidationStatus string         `json:"stream_validation_status"`
	ChainValidationStatus  string         `json:"chain_validation_status"`
	StoredBytes            int64          `json:"stored_bytes"`
	StreamSha256           sql.NullString `json:"stream_sha256"`
	StreamFromGuid         string         `json:"stream_from_guid"`
	StreamToGuid           string         `json:"stream_to_guid"`
	ChunkCount             int64          `json:"chunk_count"`
	UploadStartedAt        sql.NullString `json:"upload_started_at"`
	UploadCompletedAt      sql.NullString `json:"upload_completed_at"`
	FailureReason          sql.NullString `json:"failure_reason"`
}

func (q *Queries) ListDatasetSnapshots(ctx context.Context, datasetID string) ([]ListDatasetSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatasetSnapshots, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDatasetSnapshotsRow
	for rows.Next() {
		var i ListDatasetSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentSnapshotID,
			&i.ManifestObjectKey,
			&i.Status,
			&i.StreamValidationStatus,
			&i.ChainValidationStatus,
			&i.StoredBytes,
			&i.StreamSha256,
			&i.StreamFromGuid,
			&i.StreamToGuid,
			&i.ChunkCount,
			&i.UploadStartedAt,
			&i.UploadCompletedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasetSummaries = `-- name: ListDatasetSummaries :many
SELECT d.id AS dataset_id,
       src.name AS source_name,
       p.name AS pool_name,
       d.path AS dataset_path,
       count(CASE WHEN s.status = 'committed' THEN 1 END) AS snapshot_count,
       CAST(coalesce((
         SELECT latest.name
         FROM snapshots latest
         WHERE latest.dataset_id = d.id
         ORDER BY coalesce(latest.upload_completed_at, latest.created_at) DESC
         LIMIT 1
       ), '') AS TEXT) AS latest_snapshot_name,
       CAST(coalesce((
         SELECT valid.name
         FROM snapshots valid
         WHERE valid.dataset_id = d.id
           AND valid.status = 'committed'
           AND valid.chain_validation_status = 'succeeded'
         ORDER BY coalesce(valid.upload_completed_at, valid.created_at) DESC
         LIMIT 1
       ), '') AS TEXT) AS latest_chain_valid_snapshot_name,
       CAST(coalesce(sum(CASE WHEN s.status = 'committed' AND s.chain_validation_status = 'failed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS failed_validation_count,
       CAST(coalesce(sum(CASE WHEN s.status = 'committed' THEN s.stored_bytes ELSE 0 END), 0) AS INTEGER) AS stored_bytes,
       CAST(coalesce(max(s.upload_completed_at), '') AS TEXT) AS latest_upload_at
FROM datasets d
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
LEFT JOIN snapshots s ON s.dataset_id = d.id
GROUP BY d.id, src.name, p.name, d.path
ORDER BY latest_upload_at DESC, source_name ASC, pool_name ASC, dataset_path ASC
`

type ListDatasetSummariesRow struct {
	DatasetID                    string `json:"dataset_id"`
	SourceName                   string `json:"source_name"`
	PoolName                     string `json:"pool_name"`
	DatasetPath                  string `json:"dataset_path"`
	SnapshotCount                int64  `json:"snapshot_count"`
	LatestSnapshotName           string `json:"latest_snapshot_name"`
	LatestChainValidSnapshotName string `json:"latest_chain_valid_snapshot_name"`
	FailedValidationCount        int64  `json:"failed_validation_count"`
	StoredBytes                  int64  `json:"stored_bytes"`
	LatestUploadAt               string `json:"latest_upload_at"`
}

func (q *Queries) ListDatasetSummaries(ctx context.Context) ([]ListDatasetSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatasetSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDatasetSummariesRow
	for rows.Next() {
		var i ListDatasetSummariesRow
		if err := rows.Scan(
			&i.DatasetID,
			&i.SourceName,
			&i.PoolName,
			&i.DatasetPath,
			&i.SnapshotCount,
			&i.LatestSnapshotName,
			&i.LatestChainValidSnapshotName,
			&i.FailedValidationCount,
			&i.StoredBytes,
			&i.LatestUploadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestValidationJobs = `-- name: ListLatestValidationJobs :many
SELECT v.id,
       v.snapshot_id,
       v.type,
       v.executor,
       v.status,
       v.started_at,
       v.completed_at,
       v.result_summary,
       s.name AS snapshot_name,
       d.path AS dataset_path,
       src.name AS source_name,
       p.name AS pool_name
FROM validation_jobs v
JOIN snapshots s ON s.id = v.snapshot_id
JOIN datasets d ON d.id = s.dataset_id
JOIN sources src ON src.id = d.source_id
JOIN pools p ON p.id = d.pool_id
ORDER BY coalesce(v.completed_at, v.started_at, '') DESC
LIMIT ?
`

type ListLatestValidationJobsRow struct {
	ID            string         `json:"id"`
	SnapshotID    sql.NullString `json:"snapshot_id"`
	Type          string         `json:"type"`
	Executor      string         `json:"executor"`
	Status        string         `json:"status"`
	StartedAt     sql.NullString `json:"started_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
	ResultSummary sql.NullString `json:"result_summary"`
	SnapshotName  string         `json:"snapshot_name"`
	DatasetPath   string         `json:"dataset_path"`
	SourceName    string         `json:"source_name"`
	PoolName      string         `json:"pool_name"`
}

func (q *Queries) ListLatestValidationJobs(ctx context.Context, limit int64) ([]ListLatestValidationJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestValidationJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestValidationJobsRow
	for rows.Next() {
		var i ListLatestValidationJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Type,
			&i.Executor,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ResultSummary,
			&i.SnapshotName,
			&i.DatasetPath,
			&i.SourceName,
			&i.PoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCleanupOperations = `-- name: ListPendingCleanupOperations :many
SELECT id, dataset_id, snapshot_id
FROM operations
WHERE type = 'cleanup'
  AND status IN ('queued', 'running')
ORDER BY started_at ASC
LIMIT ?
`

type ListPendingCleanupOperationsRow struct {
	ID         string         `json:"id"`
	DatasetID  sql.NullString `json:"dataset_id"`
	SnapshotID sql.NullString `json:"snapshot_id"`
}

func (q *Queries) ListPendingCleanupOperations(ctx context.Context, limit int64) ([]ListPendingCleanupOperationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCleanupOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingCleanupOperationsRow
	for rows.Next() {
		var i ListPendingCleanupOperationsRow
		if err := rows.Scan(&i.ID, &i.DatasetID, &i.SnapshotID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHKeys = `-- name: ListSSHKeys :many
SELECT id, name, public_key, fingerprint_sha256, created_at, last_used_at
FROM ssh_keys
ORDER BY created_at DESC
`

func (q *Queries) ListSSHKeys(ctx context.Context) ([]SshKey, error) {
	rows, err := q.db.QueryContext(ctx, listSSHKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshKey
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicKey,
			&i.FingerprintSha256,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotChunks = `-- name: ListSnapshotChunks :many
SELECT id, snapshot_id, upload_session_id, chunk_index, object_key, size_bytes, zfs_offset_start, zfs_offset_end, sha256, status, created_at, completed_at
FROM snapshot_chunks
WHERE snapshot_id = ?
ORDER BY chunk_index ASC
`

func (q *Queries) ListSnapshotChunks(ctx context.Context, snapshotID string) ([]SnapshotChunk, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotChunks, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotChunk
	for rows.Next() {
		var i SnapshotChunk
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.UploadSessionID,
			&i.ChunkIndex,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ZfsOffsetStart,
			&i.ZfsOffsetEnd,
			&i.Sha256,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotObjectKeys = `-- name: ListSnapshotObjectKeys :many
SELECT snapshot_chunks.object_key
FROM snapshot_chunks
WHERE snapshot_chunks.snapshot_id = ?
UNION
SELECT manifest_object_key AS object_key
FROM snapshots
WHERE snapshots.id = ?
  AND snapshots.manifest_object_key IS NOT NULL
  AND snapshots.manifest_object_key != ''
`

type ListSnapshotObjectKeysParams struct {
	SnapshotID string `json:"snapshot_id"`
	ID         string `json:"id"`
}

func (q *Queries) ListSnapshotObjectKeys(ctx context.Context, arg ListSnapshotObjectKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotObjectKeys, arg.SnapshotID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotRestoreChain = `-- name: ListSnapshotRestoreChain :many
WITH RECURSIVE chain(depth, id, name, parent_snapshot_id, manifest_object_key, status) AS (
  SELECT 0, s.id, s.name, s.parent_snapshot_id, s.manifest_object_key, s.status
  FROM snapshots s
  WHERE s.id = ?
  UNION ALL
  SELECT chain.depth + 1, parent.id, parent.name, parent.parent_snapshot_id, parent.manifest_object_key, parent.status
  FROM snapshots parent
  JOIN chain ON chain.parent_snapshot_id = parent.id
)
SELECT id, name, parent_snapshot_id, manifest_object_key, status
FROM chain
ORDER BY depth DESC
`

type ListSnapshotRestoreChainRow struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	ParentSnapshotID  sql.NullString `json:"parent_snapshot_id"`
	ManifestObjectKey sql.NullString `json:"manifest_object_key"`
	Status            string         `json:"status"`
}

func (q *Queries) ListSnapshotRestoreChain(ctx context.Context, id string) ([]ListSnapshotRestoreChainRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotRestoreChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotRestoreChainRow
	for rows.Next() {
		var i ListSnapshotRestoreChainRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentSnapshotID,
			&i.ManifestObjectKey,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsDueForValidation = `-- name: ListSnapshotsDueForValidation :many
SELECT s.id
FROM snapshots s
WHERE s.status = 'committed'
  AND (
    s.chain_validation_status != 'succeeded'
    OR NOT EXISTS (
      SELECT 1
      FROM validation_jobs v
      WHERE v.snapshot_id = s.id
        AND v.type = 'restore_check'
        AND v.status = 'succeeded'
        AND v.completed_at >= strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-24 hours')
    )
  )
ORDER BY coalesce(s.upload_completed_at, s.created_at) ASC
LIMIT ?
`

func (q *Queries) ListSnapshotsDueForValidation(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsDueForValidation, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleUploadSessions = `-- name: ListStaleUploadSessions :many
SELECT id, dataset_id, snapshot_id, target_snapshot_name, base_snapshot_id, status,
       chunk_size_bytes, current_chunk_index, chunks_completed, bytes_received, stream_sha256,
       manifest_object_key, started_at, last_heartbeat_at, completed_at, failure_reason
FROM upload_sessions
WHERE status IN ('pending', 'uploading', 'writing_chunk', 'committing_manifest', 'committing_catalog')
  AND last_heartbeat_at < ?
ORDER BY last_heartbeat_at ASC
LIMIT ?
`

type ListStaleUploadSessionsParams struct {
	LastHeartbeatAt string `json:"last_heartbeat_at"`
	Limit           int64  `json:"limit"`
}

func (q *Queries) ListStaleUploadSessions(ctx context.Context, arg ListStaleUploadSessionsParams) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, listStaleUploadSessions, arg.LastHeartbeatAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.SnapshotID,
			&i.TargetSnapshotName,
			&i.BaseSnapshotID,
			&i.Status,
			&i.ChunkSizeBytes,
			&i.CurrentChunkIndex,
			&i.ChunksCompleted,
			&i.BytesReceived,
			&i.StreamSha256,
			&i.ManifestObjectKey,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.CompletedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadSessionChunks = `-- name: ListUploadSessionChunks :many
SELECT id, snapshot_id, upload_session_id, chunk_index, object_key, size_bytes, zfs_offset_start, zfs_offset_end, sha256, status, created_at, completed_at
FROM snapshot_chunks
WHERE upload_session_id = ?
ORDER BY chunk_index ASC
`

func (q *Queries) ListUploadSessionChunks(ctx context.Context, uploadSessionID string) ([]SnapshotChunk, error) {
	rows, err := q.db.QueryContext(ctx, listUploadSessionChunks, uploadSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotChunk
	for rows.Next() {
		var i SnapshotChunk
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.UploadSessionID,
			&i.ChunkIndex,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ZfsOffsetStart,
			&i.ZfsOffsetEnd,
			&i.Sha256,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOperationRunning = `-- name: MarkOperationRunning :exec
UPDATE operations
SET status = 'running', summary = ?, failure_reason = NULL, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), completed_at = NULL
WHERE id = ?
`

type MarkOperationRunningParams struct {
	Summary sql.NullString `json:"summary"`
	ID      string         `json:"id"`
}

func (q *Queries) MarkOperationRunning(ctx context.Context, arg MarkOperationRunningParams) error {
	_, err := q.db.ExecContext(ctx, markOperationRunning, arg.Summary, arg.ID)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeAPIToken, id)
	return err
}

const setUploadManifestObjectKey = `-- name: SetUploadManifestObjectKey :exec
UPDATE upload_sessions
SET status = 'committing_catalog', manifest_object_key = ?, last_heartbeat_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetUploadManifestObjectKeyParams struct {
	ManifestObjectKey sql.NullString `json:"manifest_object_key"`
	ID                string         `json:"id"`
}

func (q *Queries) SetUploadManifestObjectKey(ctx context.Context, arg SetUploadManifestObjectKeyParams) error {
	_, err := q.db.ExecContext(ctx, setUploadManifestObjectKey, arg.ManifestObjectKey, arg.ID)
	return err
}

const sumStoredBytes = `-- name: SumStoredBytes :one
SELECT CAST(coalesce(sum(stored_bytes), 0) AS INTEGER) AS stored_bytes
FROM snapshots
WHERE status = 'committed'
`

func (q *Queries) SumStoredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumStoredBytes)
	var stored_bytes int64
	err := row.Scan(&stored_bytes)
	return stored_bytes, err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens
SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) TouchAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, id)
	return err
}

const touchDataset = `-- name: TouchDataset :exec
UPDATE datasets
SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) TouchDataset(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchDataset, id)
	return err
}

const touchPool = `-- name: TouchPool :exec
UPDATE pools
SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) TouchPool(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchPool, id)
	return err
}

const touchSSHKey = `-- name: TouchSSHKey :exec
UPDATE ssh_keys
SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) TouchSSHKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSSHKey, id)
	return err
}

const touchSource = `-- name: TouchSource :exec
UPDATE sources
SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) TouchSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSource, id)
	return err
}

const updateAdminPasswordHash = `-- name: UpdateAdminPasswordHash :exec
INSERT INTO admin_credentials (singleton, password_hash)
VALUES (1, ?)
ON CONFLICT(singleton) DO UPDATE SET password_hash = excluded.password_hash
`

func (q *Queries) UpdateAdminPasswordHash(ctx context.Context, passwordHash sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateAdminPasswordHash, passwordHash)
	return err
}

const updateOperationStatus = `-- name: UpdateOperationStatus :exec
UPDATE operations
SET status = ?, summary = ?, failure_reason = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateOperationStatusParams struct {
	Status        string         `json:"status"`
	Summary       sql.NullString `json:"summary"`
	FailureReason sql.NullString `json:"failure_reason"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateOperationStatus(ctx context.Context, arg UpdateOperationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOperationStatus,
		arg.Status,
		arg.Summary,
		arg.FailureReason,
		arg.ID,
	)
	return err
}

const updateSnapshotChainValidationStatus = `-- name: UpdateSnapshotChainValidationStatus :exec
UPDATE snapshots
SET chain_validation_status = ?
WHERE id = ?
`

type UpdateSnapshotChainValidationStatusParams struct {
	ChainValidationStatus string `json:"chain_validation_status"`
	ID                    string `json:"id"`
}

func (q *Queries) UpdateSnapshotChainValidationStatus(ctx context.Context, arg UpdateSnapshotChainValidationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSnapshotChainValidationStatus, arg.ChainValidationStatus, arg.ID)
	return err
}

const updateSnapshotStreamValidationStatus = `-- name: UpdateSnapshotStreamValidationStatus :exec
UPDATE snapshots
SET stream_validation_status = ?
WHERE id = ?
`

type UpdateSnapshotStreamValidationStatusParams struct {
	StreamValidationStatus string `json:"stream_validation_status"`
	ID                     string `json:"id"`
}

func (q *Queries) UpdateSnapshotStreamValidationStatus(ctx context.Context, arg UpdateSnapshotStreamValidationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSnapshotStreamValidationStatus, arg.StreamValidationStatus, arg.ID)
	return err
}

const updateUploadProgress = `-- name: UpdateUploadProgress :exec
UPDATE upload_sessions
SET status = ?, current_chunk_index = ?, chunks_completed = ?, bytes_received = ?, last_heartbeat_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateUploadProgressParams struct {
	Status            string `json:"status"`
	CurrentChunkIndex int64  `json:"current_chunk_index"`
	ChunksCompleted   int64  `json:"chunks_completed"`
	BytesReceived     int64  `json:"bytes_received"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadProgress,
		arg.Status,
		arg.CurrentChunkIndex,
		arg.ChunksCompleted,
		arg.BytesReceived,
		arg.ID,
	)
	return err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :exec
UPDATE upload_sessions
SET status = ?, last_heartbeat_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateUploadStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadStatus, arg.Status, arg.ID)
	return err
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSetting, arg.Key, arg.Value)
	return err
}
