// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AdminCredential struct {
	Singleton    int64          `json:"singleton"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    string         `json:"created_at"`
}

type ApiToken struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	TokenHash   string         `json:"token_hash"`
	TokenPrefix string         `json:"token_prefix"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type AppSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type CatalogBackup struct {
	ID                string         `json:"id"`
	OperationID       sql.NullString `json:"operation_id"`
	ObjectKey         string         `json:"object_key"`
	MetadataObjectKey sql.NullString `json:"metadata_object_key"`
	SizeBytes         int64          `json:"size_bytes"`
	ChecksumSha256    string         `json:"checksum_sha256"`
	StartedAt         string         `json:"started_at"`
	CompletedAt       sql.NullString `json:"completed_at"`
	Status            string         `json:"status"`
	FailureReason     sql.NullString `json:"failure_reason"`
}

type Dataset struct {
	ID          string         `json:"id"`
	SourceID    string         `json:"source_id"`
	PoolID      string         `json:"pool_id"`
	Path        string         `json:"path"`
	DisplayName string         `json:"display_name"`
	CreatedAt   string         `json:"created_at"`
	LastSeenAt  sql.NullString `json:"last_seen_at"`
}

type Operation struct {
	ID              string         `json:"id"`
	Type            string         `json:"type"`
	Status          string         `json:"status"`
	SourceID        sql.NullString `json:"source_id"`
	PoolID          sql.NullString `json:"pool_id"`
	DatasetID       sql.NullString `json:"dataset_id"`
	SnapshotID      sql.NullString `json:"snapshot_id"`
	UploadSessionID sql.NullString `json:"upload_session_id"`
	ValidationJobID sql.NullString `json:"validation_job_id"`
	StartedAt       string         `json:"started_at"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	Summary         sql.NullString `json:"summary"`
	FailureReason   sql.NullString `json:"failure_reason"`
}

type Pool struct {
	ID         string         `json:"id"`
	SourceID   string         `json:"source_id"`
	Name       string         `json:"name"`
	CreatedAt  string         `json:"created_at"`
	LastSeenAt sql.NullString `json:"last_seen_at"`
}

type Snapshot struct {
	ID                     string         `json:"id"`
	DatasetID              string         `json:"dataset_id"`
	Name                   string         `json:"name"`
	ParentSnapshotID       sql.NullString `json:"parent_snapshot_id"`
	ManifestObjectKey      sql.NullString `json:"manifest_object_key"`
	Status                 string         `json:"status"`
	StreamValidationStatus string         `json:"stream_validation_status"`
	ChainValidationStatus  string         `json:"chain_validation_status"`
	LogicalBytes           sql.NullInt64  `json:"logical_bytes"`
	StoredBytes            int64          `json:"stored_bytes"`
	StreamSha256           sql.NullString `json:"stream_sha256"`
	StreamFromGuid         string         `json:"stream_from_guid"`
	StreamToGuid           string         `json:"stream_to_guid"`
	ChunkCount             int64          `json:"chunk_count"`
	CreatedAt              string         `json:"created_at"`
	UploadStartedAt        sql.NullString `json:"upload_started_at"`
	UploadCompletedAt      sql.NullString `json:"upload_completed_at"`
	FailureReason          sql.NullString `json:"failure_reason"`
}

type SnapshotChunk struct {
	ID              string         `json:"id"`
	SnapshotID      string         `json:"snapshot_id"`
	UploadSessionID string         `json:"upload_session_id"`
	ChunkIndex      int64          `json:"chunk_index"`
	ObjectKey       string         `json:"object_key"`
	SizeBytes       int64          `json:"size_bytes"`
	ZfsOffsetStart  int64          `json:"zfs_offset_start"`
	ZfsOffsetEnd    int64          `json:"zfs_offset_end"`
	Sha256          string         `json:"sha256"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
}

type Source struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedAt   string         `json:"created_at"`
	LastSeenAt  sql.NullString `json:"last_seen_at"`
}

type SshKey struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	PublicKey         string         `json:"public_key"`
	FingerprintSha256 string         `json:"fingerprint_sha256"`
	CreatedAt         string         `json:"created_at"`
	LastUsedAt        sql.NullString `json:"last_used_at"`
}

type UploadSession struct {
	ID                 string         `json:"id"`
	DatasetID          string         `json:"dataset_id"`
	SnapshotID         sql.NullString `json:"snapshot_id"`
	TargetSnapshotName string         `json:"target_snapshot_name"`
	BaseSnapshotID     sql.NullString `json:"base_snapshot_id"`
	Status             string         `json:"status"`
	ChunkSizeBytes     int64          `json:"chunk_size_bytes"`
	CurrentChunkIndex  int64          `json:"current_chunk_index"`
	ChunksCompleted    int64          `json:"chunks_completed"`
	BytesReceived      int64          `json:"bytes_received"`
	StreamSha256       sql.NullString `json:"stream_sha256"`
	ManifestObjectKey  sql.NullString `json:"manifest_object_key"`
	StartedAt          string         `json:"started_at"`
	LastHeartbeatAt    string         `json:"last_heartbeat_at"`
	CompletedAt        sql.NullString `json:"completed_at"`
	FailureReason      sql.NullString `json:"failure_reason"`
}

type ValidationJob struct {
	ID            string         `json:"id"`
	SnapshotID    sql.NullString `json:"snapshot_id"`
	Type          string         `json:"type"`
	Executor      string         `json:"executor"`
	Status        string         `json:"status"`
	LogsObjectKey sql.NullString `json:"logs_object_key"`
	StartedAt     sql.NullString `json:"started_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
	ResultSummary sql.NullString `json:"result_summary"`
}
