// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CommitSnapshot(ctx context.Context, arg CommitSnapshotParams) error
	CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) error
	CompleteValidationJob(ctx context.Context, arg CompleteValidationJobParams) error
	CountCommittedDescendants(ctx context.Context, parentSnapshotID sql.NullString) (int64, error)
	CountCommittedSnapshots(ctx context.Context) (int64, error)
	CountDatasets(ctx context.Context) (int64, error)
	CountFailedUploads(ctx context.Context) (int64, error)
	CountFailedValidations(ctx context.Context) (int64, error)
	CountSources(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error
	CreateCatalogBackup(ctx context.Context, arg CreateCatalogBackupParams) error
	CreateDataset(ctx context.Context, arg CreateDatasetParams) error
	CreateOperation(ctx context.Context, arg CreateOperationParams) error
	CreatePendingSnapshot(ctx context.Context, arg CreatePendingSnapshotParams) error
	CreatePool(ctx context.Context, arg CreatePoolParams) error
	CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) error
	CreateSnapshotChunk(ctx context.Context, arg CreateSnapshotChunkParams) error
	CreateSource(ctx context.Context, arg CreateSourceParams) error
	CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) error
	CreateValidationJob(ctx context.Context, arg CreateValidationJobParams) error
	CreateValidationOperation(ctx context.Context, arg CreateValidationOperationParams) error
	DeleteAppSetting(ctx context.Context, key string) error
	DeleteCatalogBackup(ctx context.Context, id string) error
	DeleteDataset(ctx context.Context, id string) error
	DeleteSSHKey(ctx context.Context, id string) error
	DeleteSnapshot(ctx context.Context, id string) error
	DeleteUploadSession(ctx context.Context, id string) error
	DeleteUploadSessionsBySnapshot(ctx context.Context, snapshotID sql.NullString) error
	EnsureAdminCredentials(ctx context.Context, passwordHash sql.NullString) error
	FailOperationByUploadSession(ctx context.Context, arg FailOperationByUploadSessionParams) error
	FailSnapshot(ctx context.Context, arg FailSnapshotParams) error
	FailUploadSession(ctx context.Context, arg FailUploadSessionParams) error
	FailValidationJob(ctx context.Context, arg FailValidationJobParams) error
	GetActiveAPITokenByHash(ctx context.Context, tokenHash string) (GetActiveAPITokenByHashRow, error)
	GetAdminCredentials(ctx context.Context) (AdminCredential, error)
	GetCommittedSnapshotByToGUID(ctx context.Context, arg GetCommittedSnapshotByToGUIDParams) (GetCommittedSnapshotByToGUIDRow, error)
	GetDatasetByPath(ctx context.Context, arg GetDatasetByPathParams) (Dataset, error)
	GetDatasetDetail(ctx context.Context, id string) (GetDatasetDetailRow, error)
	GetLatestCatalogBackup(ctx context.Context) (CatalogBackup, error)
	GetLatestOperations(ctx context.Context, limit int64) ([]GetLatestOperationsRow, error)
	GetPoolByName(ctx context.Context, arg GetPoolByNameParams) (Pool, error)
	GetSSHKeyByFingerprint(ctx context.Context, fingerprintSha256 string) (SshKey, error)
	GetSnapshotByName(ctx context.Context, arg GetSnapshotByNameParams) (Snapshot, error)
	GetSnapshotDetail(ctx context.Context, id string) (GetSnapshotDetailRow, error)
	GetSourceByName(ctx context.Context, name string) (Source, error)
	InvalidateDatasetSnapshotsForDeletion(ctx context.Context, datasetID string) error
	InvalidateSnapshotForDeletion(ctx context.Context, id string) error
	ListAPITokens(ctx context.Context) ([]ListAPITokensRow, error)
	ListAbandonedUploadSessions(ctx context.Context, arg ListAbandonedUploadSessionsParams) ([]UploadSession, error)
	ListActiveUploads(ctx context.Context) ([]ListActiveUploadsRow, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	ListCatalogBackupsOlderThan(ctx context.Context, arg ListCatalogBackupsOlderThanParams) ([]CatalogBackup, error)
	ListCommittedChildSnapshots(ctx context.Context, parentSnapshotID sql.NullString) ([]ListCommittedChildSnapshotsRow, error)
	ListCommittedSnapshotsForIdentity(ctx context.Context, arg ListCommittedSnapshotsForIdentityParams) ([]ListCommittedSnapshotsForIdentityRow, error)
	ListDatasetObjectKeys(ctx context.Context, arg ListDatasetObjectKeysParams) ([]string, error)
	ListDatasetSnapshots(ctx context.Context, datasetID string) ([]ListDatasetSnapshotsRow, error)
	ListDatasetSummaries(ctx context.Context) ([]ListDatasetSummariesRow, error)
	ListLatestValidationJobs(ctx context.Context, limit int64) ([]ListLatestValidationJobsRow, error)
	ListPendingCleanupOperations(ctx context.Context, limit int64) ([]ListPendingCleanupOperationsRow, error)
	ListSSHKeys(ctx context.Context) ([]SshKey, error)
	ListSnapshotChunks(ctx context.Context, snapshotID string) ([]SnapshotChunk, error)
	ListSnapshotObjectKeys(ctx context.Context, arg ListSnapshotObjectKeysParams) ([]string, error)
	ListSnapshotRestoreChain(ctx context.Context, id string) ([]ListSnapshotRestoreChainRow, error)
	ListSnapshotsDueForValidation(ctx context.Context, limit int64) ([]string, error)
	ListStaleUploadSessions(ctx context.Context, arg ListStaleUploadSessionsParams) ([]UploadSession, error)
	ListUploadSessionChunks(ctx context.Context, uploadSessionID string) ([]SnapshotChunk, error)
	MarkOperationRunning(ctx context.Context, arg MarkOperationRunningParams) error
	RevokeAPIToken(ctx context.Context, id string) error
	SetUploadManifestObjectKey(ctx context.Context, arg SetUploadManifestObjectKeyParams) error
	SumStoredBytes(ctx context.Context) (int64, error)
	TouchAPIToken(ctx context.Context, id string) error
	TouchDataset(ctx context.Context, id string) error
	TouchPool(ctx context.Context, id string) error
	TouchSSHKey(ctx context.Context, id string) error
	TouchSource(ctx context.Context, id string) error
	UpdateAdminPasswordHash(ctx context.Context, passwordHash sql.NullString) error
	UpdateOperationStatus(ctx context.Context, arg UpdateOperationStatusParams) error
	UpdateSnapshotChainValidationStatus(ctx context.Context, arg UpdateSnapshotChainValidationStatusParams) error
	UpdateSnapshotStreamValidationStatus(ctx context.Context, arg UpdateSnapshotStreamValidationStatusParams) error
	UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error
	UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) error
	UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error
}

var _ Querier = (*Queries)(nil)
